name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Server Dependencies
      run: |
        cd server
        npm ci

    - name: Install Client Dependencies
      run: |
        cd public
        npm ci

    - name: Run Server Tests
      run: |
        cd server
        npm test
      env:
        CI: true

    - name: Run Client Tests
      run: |
        cd public
        npm test
      env:
        CI: true

    - name: Run Linting
      run: |
        cd server && npm run lint
        cd ../public && npm run lint

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Build Client
      run: |
        cd public
        npm ci
        npm run build

    - name: Build Server
      run: |
        cd server
        npm ci
        npm run build

    # Add deployment steps here when ready for production
    # - name: Deploy to NextLayer
    #   run: |
    #     # Add NextLayer deployment commands here 