name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json

    - name: Install Server Dependencies
      run: npm ci

    - name: Run Server Tests
      run: npm test
      env:
        CI: true

    - name: Run Linting (Server)
      run: npm run lint

  test-client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./client-fe

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./client-fe/package-lock.json

    - name: Install Client Dependencies
      run: npm ci

    - name: Run Client Tests
      run: npm test
      env:
        CI: true

    - name: Run Linting (Client)
      run: npm run lint

  build-server:
    needs: test-server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Build Server
      run: |
        npm ci
        npm run build
        
  build-client:
    needs: test-server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./client-fe

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Build Client
      run: |
        npm ci
        npm run build

    # Add deployment steps here when ready for production
    # - name: Deploy to NextLayer
    #   run: |
    #     # Add NextLayer deployment commands here 
