name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
<<<<<<< HEAD
  test:
=======
  test-server:
>>>>>>> ae137c9599951f5087c6655d78591b77b50e6c9e
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

<<<<<<< HEAD
=======
    defaults:
      run:
        working-directory: ./server

>>>>>>> ae137c9599951f5087c6655d78591b77b50e6c9e
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
<<<<<<< HEAD

    - name: Install Server Dependencies
      run: |
        cd server
        npm ci

    - name: Install Client Dependencies
      run: |
        cd client-fe
        npm ci

    - name: Run Server Tests
      run: |
        cd server
        npm test
      env:
        CI: true

    - name: Run Client Tests
      run: |
        cd client-fe
        npm test
      env:
        CI: true

    - name: Run Linting
      run: |
        cd server && npm run lint
        cd ../client-fe && npm run lint

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
=======
        cache-dependency-path: ./server/package-lock.json

    - name: Install Server Dependencies
      run: npm ci

    - name: Run Server Tests
      run: npm test
      env:
        CI: true

  test-client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./client-fe

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./client-fe/package-lock.json

    - name: Install Client Dependencies
      run: npm ci

    - name: Run Client Tests
      run: npm test
      env:
        CI: true

  build-server:
    needs: test-server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./server
>>>>>>> ae137c9599951f5087c6655d78591b77b50e6c9e

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
<<<<<<< HEAD

    - name: Build Client
      run: |
        cd client-fe
        npm ci
        npm run build

    - name: Build Server
      run: |
        cd server
=======
        cache-dependency-path: ./server/package-lock.json

    - name: Build Server
      run: |
        npm ci
        npm run build
        
  build-client:
    needs: test-server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./client-fe

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ./client-fe/package-lock.json

    - name: Build Client
      run: |
>>>>>>> ae137c9599951f5087c6655d78591b77b50e6c9e
        npm ci
        npm run build

    # Add deployment steps here when ready for production
    # - name: Deploy to NextLayer
    #   run: |
<<<<<<< HEAD
    #     # Add NextLayer deployment commands here 
=======
    #     # Add NextLayer deployment commands here 
>>>>>>> ae137c9599951f5087c6655d78591b77b50e6c9e
